on:
  push

jobs:
  runs-on: "ubuntu-latest"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v5
    with:
      python-version: '3.10' 
  - run: |
    apt-get install -Y graphviz build-essential \
      && make all
